# Generated by Django 2.1.7 on 2021-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='tag',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
