# Generated by Django 2.1.7 on 2021-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(default='P', max_length=255),
        ),
    ]
