# Generated by Django 2.1.7 on 2021-04-09 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
