# Generated by Django 2.1.7 on 2021-04-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_history_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='reserve_time',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
